Fix building the web UI in OBS (#3659)
## Problem

- The Web UI does not build in OBS, it prints this error:

```
[   75s] + cd agama
[   75s] + NODE_ENV=production
[   75s] + npm run build
[   76s] 
[   76s] > build
[   76s] > webpack
[   76s] 
[   77s] [webpack-cli] Failed to load '/home/abuild/rpmbuild/BUILD/agama-web-ui-22+87.f741e1d07-build/agama/webpack.config.js' config
[   77s] [webpack-cli] Error: Cannot find module 'metadata.js'
```

## Solution

- Explicitly require the `monaco-editor` NPM package
- It works fine when building locally as that is installed as a peer NPM
package, but during RPM build that fails.

## Testing

- Builds fine in a [testing OBS
project](https://build.opensuse.org/package/live_build_log/systemsmanagement:Agama:branches:fix-web-build/agama-web-ui/openSUSE_Tumbleweed/x86_64)