[web] Use the default Layout import in test-utils.js
To avoid having the failure

> TypeError: Cannot read properties of undefined (reading 'mockComponent')

when using the recently introduced mockComonent function for components living
in the layout namespace.

See https://github.com/yast/d-installer/pull/392#discussion_r1067485958