fix(web): move keyboard reminder to an internal component
To avoid application crashing with

> Error: useInstallerL10n must be used within a InstallerL10nContext
>   at useInstallerL10n (http://localhost:8080/index.js:57706:11)
>   at PasswordInput (http://localhost:8080/index.62413e0223d80064660e.hot-update.js:322:99)

due to the usage of the useInstallerL10n hook.

Moving the keyboard reminder into an isolated internal component prevents the hook from executing
when mounting PasswordInput with the `showKeyboardHint={false}` prop.