[web][doc] Include src/context as entry point
And fix issues while importing some type defintions from clients because
a wrong path.

> Error: Expected a symbol for node with kind Identifier at
> /home/dgdavid/development/agama/web/src/context/l10n.jsx:27

> Error: Expected a symbol for node with kind Identifier at
> /home/dgdavid/development/agama/web/src/context/product.jsx:27

Imports for @typedef in these files were  using `src/clients/` instead
of `src/client`.