test: SoftwareStore::store happy
Note the `when.(...).body("{JSON object}")` part

where the JSON must match what the client sends,
otherwise the mock server will respond with a 404,
and the test will rightly fail with:
```
Error: BackendError(404, "{\"message\":\"Request did not match any route or mock\"}")
```

The problem is that if you compose that JSON according to your best understanding of the client but make a typo, you are still left with that unhelpful 404.

These 3 parts were all need to arrive at a working string:

1. Enable httpmock logging by calling `env_logger::init();` at the start of the test function.
2. Show the request, by enabling the logging at runtime, at the right level: (`test_setting_software` is a partial match on the test name).

```console
(cd rust; RUST_LOG=httpmock=debug cargo test test_setting_software)
```

If you don't like typing, the really important bits are these. httpmock will also log the more detailed Trace level but it does not get in the way
```console
RUST_LOG=httpmock cargo test
```

3. Unfortunately the request will be logged not as text but as an array of bytes shown numerically. [Process the output with this script to extract the text.][extract]

[extract]: https://gist.github.com/mvidner/0e22ea82abecb44b469841929e5ec279#file-httpmock_body-rb