web: fix ReferenceError after React Router v7 migration
After migrating to React Router v7, the test suite fails with the
following error:

> ReferenceError: TextEncoder is not defined

This appears to be due to an unimplemented TextEncoder in jsdom. To
resolve this, we follow the same workaround as React Router, as outlined
in https://github.com/remix-run/react-router/issues/12363#issuecomment-2496226528