initialize InstallationPhase (bsc#1245760)
Fix error at /api/manager/installer:
initialize the backend value
for org.opensuse.Agama1.Manager.CurrentInstallationPhase

otherwise it is nil and we get:
agama-web-server[3392]: Server return error Agama service error: D-Bus service error: org.freedesktop.DBus.Error.Failed: nil is not a member of 0..4294967295; caused by 1 sender=:1.2 -> dest=org.opensuse.Agama.Manager1 serial=104 reply_serial= path=/org/opensuse/Agama/Manager1; interface=org.freedesktop.DBus.Properties; member=Get error_name=