[web][doc] Include src/components as entry point
Also fixes a bad written link and some imports for @typedef which were
either, using a wrong path or missing a namespace.

Just for future references, find below errors related with these wrong
imports,

> Error: Expected a symbol for node with kind Identifier at...
> AssertionError [ERR_ASSERTION]: Missing symbol when converting import type node...