[web] Ensure validity of Selector children
TypeScript complained about:

> src/components/core/Selector.jsx:115:41 - error TS2339: Property 'props' does not exist on type 'ReactNode'.
> 115       { React.Children.map(children, ({ props: { id, key, children } }) => {

And it was right because a React child could be something without
`props`, like undefined or just a plain string[1]. Thus, the easy way of
protecting the code and pleasing TypeScript is checking that that child
is a valid React element.[2]

However, this is yet another hint warning about that maybe the selector
should stop doing a children manipulation and goes for a
`options`/`renderOption` props or simila approach instead, although it
defeats the idea of having an expressive JSX-based markup.

[1] https://react.dev/reference/react/Children#children-map-caveats
[2] https://react.dev/reference/react/isValidElement#reference